### PR TITLE
Add i18n configmap values

### PR DESCRIPTION
**Pull request by parc-jason**
Signed-off-by: Jason Sherman <jsherman@parcsystems.ca>

Add new values for the BPA Config Map. This will set the Browser title, and internationalization locale and fallbackLocale.

### CODE REVIEW

**Comment by frank-bee** [comment]
@parc-jason  after we talked today I thought again about the 2 names ( browser name and name).

For me/ us it is just important to have suitable defaults which allows to stand-up bpas with "zero config"
It is fine with having 1 or 2 parameters (I think for production usage both can be the same).

Maybe there could be this "overwrite logic":

IF "overwrite_name" != ""  THEN name = overwrite_name 
ELSE use the chart release name

IF "overwrite_browsername" != ""  THEN browsername = overwrite_browsername
ELSIF "overwrite_name" != ""  THEN browsername = overwrite_name 
ELSE use the chart release name

**Comment by frank-bee** [comment]
BTW, If you used the the tpl function in the configmap, the user can even use templates in his value (e.g. make use of helm release  name or so), see e.g. 
`AGENT_NAME: {{ tpl .Values.bpa.config.name . | quote }}`

**Comment by parc-jason** [comment]
> @parc-jason after we talked today I thought again about the 2 names ( browser name and name).
> 
> For me/ us it is just important to have suitable defaults which allows to stand-up bpas with "zero config"
> It is fine with having 1 or 2 parameters (I think for production usage both can be the same).
> 
> Maybe there could be this "overwrite logic":
> 
> IF "overwrite_name" != "" THEN name = overwrite_name
> ELSE use the capitalized chart release name
> 
> IF "overwrite_browsername" != "" THEN browsername = overwrite_browsername
> ELSIF "overwrite_name" != "" THEN browsername = overwrite_name
> ELSE use the capitalized chart release name

So something where the `title` can be set, but by default it is the `name`...

```  config:
    security:
      enabled: true
    bootstrap:
      username: admin
      password: changeme
    resolver:
      url: "{{ printf \"https://resolver%s\" .Values.global.ingressSuffix }}"
    ledger:
      browserUrlOverride: ""
    name: "{{ camelcase .Release.Name }}"
    scheme: https
    web:
      only: false
    did:
      # -- Will be otherwise calculated based on global.ledger config
      prefixOverride: ""
    creddef:
      revocationRegistrySize: 3000
    imprint:
      enabled: false
      url: "{{ printf \"https://bpa%s/\" .Values.global.ingressSuffix }}"
    privacyPolicy:
      enabled: false
      url: "{{ printf \"https://bpa%s/privacyPolicy\" .Values.global.ingressSuffix }}"
    title: "{{ .Values.bpa.config.name }}"
    i18n:
      locale: en
      fallbackLocale: en```

**Comment by parc-jason** [comment]
> BTW, If you use the `tpl` function in the configmap, the user can even use templates in his value (e.g. make use of helm release name or so), see e.g.
> `AGENT_NAME: {{ tpl .Values.bpa.config.name . | quote }}`

Ahh, ok - very cool.

**Comment by frank-bee** [comment]
what you described is also an option but having the templates as defaults looks very "techie".
Better would be to have 2 empty values : e.g. `overwriteName` and `overwriteTitle`
and hiding the logic I described from the user (only telling this in the description of the parameter).

**Comment by parc-jason** [comment]
> what you described is also an option but having the templates as defaults looks very "techie".
> Better would be to have 2 empty values : e.g. `overwriteName` and `overwriteTitle`
> and hiding the logic I described from the user (only telling this in the description of the parameter).

Ok, so you'd rather have logic in helpers/templates than use the `bpa.config` values directly.  I'll change it around.

**Comment by frank-bee** [comment]
@parc-jason that is nearly what I thought of. But wanted to get rid of name and title as values - having only the 2 overwrite thingy's ... I will fix the rest tomorrow!! Great work. We are constantly improving the technical dept of the chart , check.

**Comment by parc-jason** [comment]
> @parc-jason that is nearly what I thought of. But wanted to get rid of `name` and `title` as values - having only the 2 overwrite thingy's ... I will fix the rest tomorrow!! Great work. We are constantly improving the technical dept of the chart , check.

Ok, I'll leave it to you :)

**Comment by frank-bee** [comment]
for resolver and legder url I will do it similar.  and I will document at least some of our parameters.

**Comment by parc-jason** [comment]
> for resolver and legder url I will do it similar. and I will document at least some of our parameters.

sounds good, come up with a new "standard" is a good idea.
Also, no idea why the chart install is failing... 🤷‍♂️

**Comment by frank-bee** [comment]
@parc-jason hmm , I fixed some stuff , also upgraded the acapy image and the bpa image (used latest from master). but chart tests seem still to fail even if locally I was able to install the chart into our cluster in IDU.
I can look into that tomorrow again...

**Comment by frank-bee** [comment]
seems to be a kind problem ` 0/1 nodes are available: 1 node(s) had taint {node.kubernetes.io/not-ready: }, that the pod didn't tolerate.`

**Comment by frank-bee** [comment]
I merge this and look into that

**Pull request merged**
